# Generated by Django 4.0.6 on 2022-09-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('jdate', models.DateField()),
                ('phnumber', models.IntegerField(max_length=10, null=b'I01\n')),
            ],
        ),
    ]
