# Generated by Django 4.0.6 on 2022-09-01 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('jdate', models.DateField()),
                ('phnumber', models.IntegerField(max_length=10, null=True)),
            ],
        ),
    ]
