# Generated by Django 4.0.6 on 2022-09-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phnumber',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
